/**
 */
package ddsMetamodel.provider;

import ddsMetamodel.util.DdsMetamodelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DdsMetamodelItemProviderAdapterFactory extends DdsMetamodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DdsMetamodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsApplication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsApplicationItemProvider ddsApplicationItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsApplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsApplicationAdapter() {
		if (ddsApplicationItemProvider == null) {
			ddsApplicationItemProvider = new DdsApplicationItemProvider(this);
		}

		return ddsApplicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDomainParticipant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDomainParticipantItemProvider ddsDomainParticipantItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDomainParticipant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDomainParticipantAdapter() {
		if (ddsDomainParticipantItemProvider == null) {
			ddsDomainParticipantItemProvider = new DdsDomainParticipantItemProvider(this);
		}

		return ddsDomainParticipantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTopic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTopicItemProvider ddsTopicItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTopic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTopicAdapter() {
		if (ddsTopicItemProvider == null) {
			ddsTopicItemProvider = new DdsTopicItemProvider(this);
		}

		return ddsTopicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsQosProfileItemProvider ddsQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsQosProfileAdapter() {
		if (ddsQosProfileItemProvider == null) {
			ddsQosProfileItemProvider = new DdsQosProfileItemProvider(this);
		}

		return ddsQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsSubscriber} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsSubscriberItemProvider ddsSubscriberItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsSubscriber}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsSubscriberAdapter() {
		if (ddsSubscriberItemProvider == null) {
			ddsSubscriberItemProvider = new DdsSubscriberItemProvider(this);
		}

		return ddsSubscriberItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataReader} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataReaderItemProvider ddsDataReaderItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataReader}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataReaderAdapter() {
		if (ddsDataReaderItemProvider == null) {
			ddsDataReaderItemProvider = new DdsDataReaderItemProvider(this);
		}

		return ddsDataReaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsPublisher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsPublisherItemProvider ddsPublisherItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsPublisher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsPublisherAdapter() {
		if (ddsPublisherItemProvider == null) {
			ddsPublisherItemProvider = new DdsPublisherItemProvider(this);
		}

		return ddsPublisherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataWriter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataWriterItemProvider ddsDataWriterItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataWriter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataWriterAdapter() {
		if (ddsDataWriterItemProvider == null) {
			ddsDataWriterItemProvider = new DdsDataWriterItemProvider(this);
		}

		return ddsDataWriterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataModuleItemProvider ddsDataModuleItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataModuleAdapter() {
		if (ddsDataModuleItemProvider == null) {
			ddsDataModuleItemProvider = new DdsDataModuleItemProvider(this);
		}

		return ddsDataModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataStructureItemProvider ddsDataStructureItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataStructureAdapter() {
		if (ddsDataStructureItemProvider == null) {
			ddsDataStructureItemProvider = new DdsDataStructureItemProvider(this);
		}

		return ddsDataStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataFieldItemProvider ddsDataFieldItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataFieldAdapter() {
		if (ddsDataFieldItemProvider == null) {
			ddsDataFieldItemProvider = new DdsDataFieldItemProvider(this);
		}

		return ddsDataFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDomainParticipantQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDomainParticipantQosProfileItemProvider ddsDomainParticipantQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDomainParticipantQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDomainParticipantQosProfileAdapter() {
		if (ddsDomainParticipantQosProfileItemProvider == null) {
			ddsDomainParticipantQosProfileItemProvider = new DdsDomainParticipantQosProfileItemProvider(this);
		}

		return ddsDomainParticipantQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsUserDataQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsUserDataQosItemProvider ddsUserDataQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsUserDataQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsUserDataQosAdapter() {
		if (ddsUserDataQosItemProvider == null) {
			ddsUserDataQosItemProvider = new DdsUserDataQosItemProvider(this);
		}

		return ddsUserDataQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsEntityFactoryQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsEntityFactoryQosItemProvider ddsEntityFactoryQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsEntityFactoryQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsEntityFactoryQosAdapter() {
		if (ddsEntityFactoryQosItemProvider == null) {
			ddsEntityFactoryQosItemProvider = new DdsEntityFactoryQosItemProvider(this);
		}

		return ddsEntityFactoryQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTopicQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTopicQosProfileItemProvider ddsTopicQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTopicQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTopicQosProfileAdapter() {
		if (ddsTopicQosProfileItemProvider == null) {
			ddsTopicQosProfileItemProvider = new DdsTopicQosProfileItemProvider(this);
		}

		return ddsTopicQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTopicDataQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTopicDataQosItemProvider ddsTopicDataQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTopicDataQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTopicDataQosAdapter() {
		if (ddsTopicDataQosItemProvider == null) {
			ddsTopicDataQosItemProvider = new DdsTopicDataQosItemProvider(this);
		}

		return ddsTopicDataQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDurabilityQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDurabilityQosItemProvider ddsDurabilityQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDurabilityQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDurabilityQosAdapter() {
		if (ddsDurabilityQosItemProvider == null) {
			ddsDurabilityQosItemProvider = new DdsDurabilityQosItemProvider(this);
		}

		return ddsDurabilityQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDurabilityServiceQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDurabilityServiceQosItemProvider ddsDurabilityServiceQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDurabilityServiceQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDurabilityServiceQosAdapter() {
		if (ddsDurabilityServiceQosItemProvider == null) {
			ddsDurabilityServiceQosItemProvider = new DdsDurabilityServiceQosItemProvider(this);
		}

		return ddsDurabilityServiceQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDurationItemProvider ddsDurationItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDurationAdapter() {
		if (ddsDurationItemProvider == null) {
			ddsDurationItemProvider = new DdsDurationItemProvider(this);
		}

		return ddsDurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsPresentationQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsPresentationQosItemProvider ddsPresentationQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsPresentationQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsPresentationQosAdapter() {
		if (ddsPresentationQosItemProvider == null) {
			ddsPresentationQosItemProvider = new DdsPresentationQosItemProvider(this);
		}

		return ddsPresentationQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDeadlineQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDeadlineQosItemProvider ddsDeadlineQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDeadlineQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDeadlineQosAdapter() {
		if (ddsDeadlineQosItemProvider == null) {
			ddsDeadlineQosItemProvider = new DdsDeadlineQosItemProvider(this);
		}

		return ddsDeadlineQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsLatencyBudgetQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsLatencyBudgetQosItemProvider ddsLatencyBudgetQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsLatencyBudgetQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsLatencyBudgetQosAdapter() {
		if (ddsLatencyBudgetQosItemProvider == null) {
			ddsLatencyBudgetQosItemProvider = new DdsLatencyBudgetQosItemProvider(this);
		}

		return ddsLatencyBudgetQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsOwnershipQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsOwnershipQosItemProvider ddsOwnershipQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsOwnershipQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsOwnershipQosAdapter() {
		if (ddsOwnershipQosItemProvider == null) {
			ddsOwnershipQosItemProvider = new DdsOwnershipQosItemProvider(this);
		}

		return ddsOwnershipQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsOwnershipStrengthQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsOwnershipStrengthQosItemProvider ddsOwnershipStrengthQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsOwnershipStrengthQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsOwnershipStrengthQosAdapter() {
		if (ddsOwnershipStrengthQosItemProvider == null) {
			ddsOwnershipStrengthQosItemProvider = new DdsOwnershipStrengthQosItemProvider(this);
		}

		return ddsOwnershipStrengthQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsLivelinessQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsLivelinessQosItemProvider ddsLivelinessQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsLivelinessQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsLivelinessQosAdapter() {
		if (ddsLivelinessQosItemProvider == null) {
			ddsLivelinessQosItemProvider = new DdsLivelinessQosItemProvider(this);
		}

		return ddsLivelinessQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTimeBasedFilterQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTimeBasedFilterQosItemProvider ddsTimeBasedFilterQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTimeBasedFilterQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTimeBasedFilterQosAdapter() {
		if (ddsTimeBasedFilterQosItemProvider == null) {
			ddsTimeBasedFilterQosItemProvider = new DdsTimeBasedFilterQosItemProvider(this);
		}

		return ddsTimeBasedFilterQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsPartitionQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsPartitionQosItemProvider ddsPartitionQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsPartitionQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsPartitionQosAdapter() {
		if (ddsPartitionQosItemProvider == null) {
			ddsPartitionQosItemProvider = new DdsPartitionQosItemProvider(this);
		}

		return ddsPartitionQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsReliabilityQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsReliabilityQosItemProvider ddsReliabilityQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsReliabilityQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsReliabilityQosAdapter() {
		if (ddsReliabilityQosItemProvider == null) {
			ddsReliabilityQosItemProvider = new DdsReliabilityQosItemProvider(this);
		}

		return ddsReliabilityQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTransportPriorityQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTransportPriorityQosItemProvider ddsTransportPriorityQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTransportPriorityQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTransportPriorityQosAdapter() {
		if (ddsTransportPriorityQosItemProvider == null) {
			ddsTransportPriorityQosItemProvider = new DdsTransportPriorityQosItemProvider(this);
		}

		return ddsTransportPriorityQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsLifespan} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsLifespanItemProvider ddsLifespanItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsLifespan}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsLifespanAdapter() {
		if (ddsLifespanItemProvider == null) {
			ddsLifespanItemProvider = new DdsLifespanItemProvider(this);
		}

		return ddsLifespanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsHistoryQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsHistoryQosItemProvider ddsHistoryQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsHistoryQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsHistoryQosAdapter() {
		if (ddsHistoryQosItemProvider == null) {
			ddsHistoryQosItemProvider = new DdsHistoryQosItemProvider(this);
		}

		return ddsHistoryQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsResourceLimits} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsResourceLimitsItemProvider ddsResourceLimitsItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsResourceLimits}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsResourceLimitsAdapter() {
		if (ddsResourceLimitsItemProvider == null) {
			ddsResourceLimitsItemProvider = new DdsResourceLimitsItemProvider(this);
		}

		return ddsResourceLimitsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataWriterLifecycleQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataWriterLifecycleQosItemProvider ddsDataWriterLifecycleQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataWriterLifecycleQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataWriterLifecycleQosAdapter() {
		if (ddsDataWriterLifecycleQosItemProvider == null) {
			ddsDataWriterLifecycleQosItemProvider = new DdsDataWriterLifecycleQosItemProvider(this);
		}

		return ddsDataWriterLifecycleQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataReaderLifecycleQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataReaderLifecycleQosItemProvider ddsDataReaderLifecycleQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataReaderLifecycleQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataReaderLifecycleQosAdapter() {
		if (ddsDataReaderLifecycleQosItemProvider == null) {
			ddsDataReaderLifecycleQosItemProvider = new DdsDataReaderLifecycleQosItemProvider(this);
		}

		return ddsDataReaderLifecycleQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDestinationOrderQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDestinationOrderQosItemProvider ddsDestinationOrderQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDestinationOrderQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDestinationOrderQosAdapter() {
		if (ddsDestinationOrderQosItemProvider == null) {
			ddsDestinationOrderQosItemProvider = new DdsDestinationOrderQosItemProvider(this);
		}

		return ddsDestinationOrderQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsPublisherQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsPublisherQosProfileItemProvider ddsPublisherQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsPublisherQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsPublisherQosProfileAdapter() {
		if (ddsPublisherQosProfileItemProvider == null) {
			ddsPublisherQosProfileItemProvider = new DdsPublisherQosProfileItemProvider(this);
		}

		return ddsPublisherQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsGroupDataQos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsGroupDataQosItemProvider ddsGroupDataQosItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsGroupDataQos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsGroupDataQosAdapter() {
		if (ddsGroupDataQosItemProvider == null) {
			ddsGroupDataQosItemProvider = new DdsGroupDataQosItemProvider(this);
		}

		return ddsGroupDataQosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataWriterQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataWriterQosProfileItemProvider ddsDataWriterQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataWriterQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataWriterQosProfileAdapter() {
		if (ddsDataWriterQosProfileItemProvider == null) {
			ddsDataWriterQosProfileItemProvider = new DdsDataWriterQosProfileItemProvider(this);
		}

		return ddsDataWriterQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsSubscriberQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsSubscriberQosProfileItemProvider ddsSubscriberQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsSubscriberQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsSubscriberQosProfileAdapter() {
		if (ddsSubscriberQosProfileItemProvider == null) {
			ddsSubscriberQosProfileItemProvider = new DdsSubscriberQosProfileItemProvider(this);
		}

		return ddsSubscriberQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataReaderQosProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataReaderQosProfileItemProvider ddsDataReaderQosProfileItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataReaderQosProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataReaderQosProfileAdapter() {
		if (ddsDataReaderQosProfileItemProvider == null) {
			ddsDataReaderQosProfileItemProvider = new DdsDataReaderQosProfileItemProvider(this);
		}

		return ddsDataReaderQosProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDomainParticipantListener} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDomainParticipantListenerItemProvider ddsDomainParticipantListenerItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDomainParticipantListener}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDomainParticipantListenerAdapter() {
		if (ddsDomainParticipantListenerItemProvider == null) {
			ddsDomainParticipantListenerItemProvider = new DdsDomainParticipantListenerItemProvider(this);
		}

		return ddsDomainParticipantListenerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsSubscriberListener} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsSubscriberListenerItemProvider ddsSubscriberListenerItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsSubscriberListener}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsSubscriberListenerAdapter() {
		if (ddsSubscriberListenerItemProvider == null) {
			ddsSubscriberListenerItemProvider = new DdsSubscriberListenerItemProvider(this);
		}

		return ddsSubscriberListenerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsPublisherListener} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsPublisherListenerItemProvider ddsPublisherListenerItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsPublisherListener}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsPublisherListenerAdapter() {
		if (ddsPublisherListenerItemProvider == null) {
			ddsPublisherListenerItemProvider = new DdsPublisherListenerItemProvider(this);
		}

		return ddsPublisherListenerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataReaderListener} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataReaderListenerItemProvider ddsDataReaderListenerItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataReaderListener}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataReaderListenerAdapter() {
		if (ddsDataReaderListenerItemProvider == null) {
			ddsDataReaderListenerItemProvider = new DdsDataReaderListenerItemProvider(this);
		}

		return ddsDataReaderListenerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataWriterListener} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataWriterListenerItemProvider ddsDataWriterListenerItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataWriterListener}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataWriterListenerAdapter() {
		if (ddsDataWriterListenerItemProvider == null) {
			ddsDataWriterListenerItemProvider = new DdsDataWriterListenerItemProvider(this);
		}

		return ddsDataWriterListenerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTopicListener} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTopicListenerItemProvider ddsTopicListenerItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTopicListener}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTopicListenerAdapter() {
		if (ddsTopicListenerItemProvider == null) {
			ddsTopicListenerItemProvider = new DdsTopicListenerItemProvider(this);
		}

		return ddsTopicListenerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsWaitSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsWaitSetItemProvider ddsWaitSetItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsWaitSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsWaitSetAdapter() {
		if (ddsWaitSetItemProvider == null) {
			ddsWaitSetItemProvider = new DdsWaitSetItemProvider(this);
		}

		return ddsWaitSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsReadCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsReadConditionItemProvider ddsReadConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsReadCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsReadConditionAdapter() {
		if (ddsReadConditionItemProvider == null) {
			ddsReadConditionItemProvider = new DdsReadConditionItemProvider(this);
		}

		return ddsReadConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsStructuredField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsStructuredFieldItemProvider ddsStructuredFieldItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsStructuredField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsStructuredFieldAdapter() {
		if (ddsStructuredFieldItemProvider == null) {
			ddsStructuredFieldItemProvider = new DdsStructuredFieldItemProvider(this);
		}

		return ddsStructuredFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsStatusConditionItemProvider ddsStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsStatusConditionAdapter() {
		if (ddsStatusConditionItemProvider == null) {
			ddsStatusConditionItemProvider = new DdsStatusConditionItemProvider(this);
		}

		return ddsStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDomainParticipantStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDomainParticipantStatusConditionItemProvider ddsDomainParticipantStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDomainParticipantStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDomainParticipantStatusConditionAdapter() {
		if (ddsDomainParticipantStatusConditionItemProvider == null) {
			ddsDomainParticipantStatusConditionItemProvider = new DdsDomainParticipantStatusConditionItemProvider(this);
		}

		return ddsDomainParticipantStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsPublisherStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsPublisherStatusConditionItemProvider ddsPublisherStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsPublisherStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsPublisherStatusConditionAdapter() {
		if (ddsPublisherStatusConditionItemProvider == null) {
			ddsPublisherStatusConditionItemProvider = new DdsPublisherStatusConditionItemProvider(this);
		}

		return ddsPublisherStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsSubscriberStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsSubscriberStatusConditionItemProvider ddsSubscriberStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsSubscriberStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsSubscriberStatusConditionAdapter() {
		if (ddsSubscriberStatusConditionItemProvider == null) {
			ddsSubscriberStatusConditionItemProvider = new DdsSubscriberStatusConditionItemProvider(this);
		}

		return ddsSubscriberStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataWriterStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataWriterStatusConditionItemProvider ddsDataWriterStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataWriterStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataWriterStatusConditionAdapter() {
		if (ddsDataWriterStatusConditionItemProvider == null) {
			ddsDataWriterStatusConditionItemProvider = new DdsDataWriterStatusConditionItemProvider(this);
		}

		return ddsDataWriterStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsDataReaderStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsDataReaderStatusConditionItemProvider ddsDataReaderStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsDataReaderStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsDataReaderStatusConditionAdapter() {
		if (ddsDataReaderStatusConditionItemProvider == null) {
			ddsDataReaderStatusConditionItemProvider = new DdsDataReaderStatusConditionItemProvider(this);
		}

		return ddsDataReaderStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsTopicStatusCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsTopicStatusConditionItemProvider ddsTopicStatusConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsTopicStatusCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsTopicStatusConditionAdapter() {
		if (ddsTopicStatusConditionItemProvider == null) {
			ddsTopicStatusConditionItemProvider = new DdsTopicStatusConditionItemProvider(this);
		}

		return ddsTopicStatusConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.QueryCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QueryConditionItemProvider queryConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.QueryCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQueryConditionAdapter() {
		if (queryConditionItemProvider == null) {
			queryConditionItemProvider = new QueryConditionItemProvider(this);
		}

		return queryConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.GuardCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuardConditionItemProvider guardConditionItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.GuardCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuardConditionAdapter() {
		if (guardConditionItemProvider == null) {
			guardConditionItemProvider = new GuardConditionItemProvider(this);
		}

		return guardConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsSystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsSystemItemProvider ddsSystemItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsSystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsSystemAdapter() {
		if (ddsSystemItemProvider == null) {
			ddsSystemItemProvider = new DdsSystemItemProvider(this);
		}

		return ddsSystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ddsMetamodel.DdsHost} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DdsHostItemProvider ddsHostItemProvider;

	/**
	 * This creates an adapter for a {@link ddsMetamodel.DdsHost}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDdsHostAdapter() {
		if (ddsHostItemProvider == null) {
			ddsHostItemProvider = new DdsHostItemProvider(this);
		}

		return ddsHostItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (ddsApplicationItemProvider != null) ddsApplicationItemProvider.dispose();
		if (ddsDomainParticipantItemProvider != null) ddsDomainParticipantItemProvider.dispose();
		if (ddsTopicItemProvider != null) ddsTopicItemProvider.dispose();
		if (ddsQosProfileItemProvider != null) ddsQosProfileItemProvider.dispose();
		if (ddsSubscriberItemProvider != null) ddsSubscriberItemProvider.dispose();
		if (ddsDataReaderItemProvider != null) ddsDataReaderItemProvider.dispose();
		if (ddsPublisherItemProvider != null) ddsPublisherItemProvider.dispose();
		if (ddsDataWriterItemProvider != null) ddsDataWriterItemProvider.dispose();
		if (ddsDataModuleItemProvider != null) ddsDataModuleItemProvider.dispose();
		if (ddsDataStructureItemProvider != null) ddsDataStructureItemProvider.dispose();
		if (ddsDataFieldItemProvider != null) ddsDataFieldItemProvider.dispose();
		if (ddsDomainParticipantQosProfileItemProvider != null) ddsDomainParticipantQosProfileItemProvider.dispose();
		if (ddsUserDataQosItemProvider != null) ddsUserDataQosItemProvider.dispose();
		if (ddsEntityFactoryQosItemProvider != null) ddsEntityFactoryQosItemProvider.dispose();
		if (ddsTopicQosProfileItemProvider != null) ddsTopicQosProfileItemProvider.dispose();
		if (ddsTopicDataQosItemProvider != null) ddsTopicDataQosItemProvider.dispose();
		if (ddsDurabilityQosItemProvider != null) ddsDurabilityQosItemProvider.dispose();
		if (ddsDurabilityServiceQosItemProvider != null) ddsDurabilityServiceQosItemProvider.dispose();
		if (ddsDurationItemProvider != null) ddsDurationItemProvider.dispose();
		if (ddsPresentationQosItemProvider != null) ddsPresentationQosItemProvider.dispose();
		if (ddsDeadlineQosItemProvider != null) ddsDeadlineQosItemProvider.dispose();
		if (ddsLatencyBudgetQosItemProvider != null) ddsLatencyBudgetQosItemProvider.dispose();
		if (ddsOwnershipQosItemProvider != null) ddsOwnershipQosItemProvider.dispose();
		if (ddsOwnershipStrengthQosItemProvider != null) ddsOwnershipStrengthQosItemProvider.dispose();
		if (ddsLivelinessQosItemProvider != null) ddsLivelinessQosItemProvider.dispose();
		if (ddsTimeBasedFilterQosItemProvider != null) ddsTimeBasedFilterQosItemProvider.dispose();
		if (ddsPartitionQosItemProvider != null) ddsPartitionQosItemProvider.dispose();
		if (ddsReliabilityQosItemProvider != null) ddsReliabilityQosItemProvider.dispose();
		if (ddsTransportPriorityQosItemProvider != null) ddsTransportPriorityQosItemProvider.dispose();
		if (ddsLifespanItemProvider != null) ddsLifespanItemProvider.dispose();
		if (ddsHistoryQosItemProvider != null) ddsHistoryQosItemProvider.dispose();
		if (ddsResourceLimitsItemProvider != null) ddsResourceLimitsItemProvider.dispose();
		if (ddsDataWriterLifecycleQosItemProvider != null) ddsDataWriterLifecycleQosItemProvider.dispose();
		if (ddsDataReaderLifecycleQosItemProvider != null) ddsDataReaderLifecycleQosItemProvider.dispose();
		if (ddsDestinationOrderQosItemProvider != null) ddsDestinationOrderQosItemProvider.dispose();
		if (ddsPublisherQosProfileItemProvider != null) ddsPublisherQosProfileItemProvider.dispose();
		if (ddsGroupDataQosItemProvider != null) ddsGroupDataQosItemProvider.dispose();
		if (ddsDataWriterQosProfileItemProvider != null) ddsDataWriterQosProfileItemProvider.dispose();
		if (ddsSubscriberQosProfileItemProvider != null) ddsSubscriberQosProfileItemProvider.dispose();
		if (ddsDataReaderQosProfileItemProvider != null) ddsDataReaderQosProfileItemProvider.dispose();
		if (ddsDomainParticipantListenerItemProvider != null) ddsDomainParticipantListenerItemProvider.dispose();
		if (ddsSubscriberListenerItemProvider != null) ddsSubscriberListenerItemProvider.dispose();
		if (ddsPublisherListenerItemProvider != null) ddsPublisherListenerItemProvider.dispose();
		if (ddsDataReaderListenerItemProvider != null) ddsDataReaderListenerItemProvider.dispose();
		if (ddsDataWriterListenerItemProvider != null) ddsDataWriterListenerItemProvider.dispose();
		if (ddsTopicListenerItemProvider != null) ddsTopicListenerItemProvider.dispose();
		if (ddsWaitSetItemProvider != null) ddsWaitSetItemProvider.dispose();
		if (ddsReadConditionItemProvider != null) ddsReadConditionItemProvider.dispose();
		if (ddsStructuredFieldItemProvider != null) ddsStructuredFieldItemProvider.dispose();
		if (ddsStatusConditionItemProvider != null) ddsStatusConditionItemProvider.dispose();
		if (ddsDomainParticipantStatusConditionItemProvider != null) ddsDomainParticipantStatusConditionItemProvider.dispose();
		if (ddsPublisherStatusConditionItemProvider != null) ddsPublisherStatusConditionItemProvider.dispose();
		if (ddsSubscriberStatusConditionItemProvider != null) ddsSubscriberStatusConditionItemProvider.dispose();
		if (ddsDataWriterStatusConditionItemProvider != null) ddsDataWriterStatusConditionItemProvider.dispose();
		if (ddsDataReaderStatusConditionItemProvider != null) ddsDataReaderStatusConditionItemProvider.dispose();
		if (ddsTopicStatusConditionItemProvider != null) ddsTopicStatusConditionItemProvider.dispose();
		if (queryConditionItemProvider != null) queryConditionItemProvider.dispose();
		if (guardConditionItemProvider != null) guardConditionItemProvider.dispose();
		if (ddsSystemItemProvider != null) ddsSystemItemProvider.dispose();
		if (ddsHostItemProvider != null) ddsHostItemProvider.dispose();
	}

}
